backend:
  name: github
  repo: Blicksel/The-Repository
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "src/content/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image", required: false }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "tags", label: "Tags", widget: "list" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "publishDate", label: "Publish Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
  - name: "reviews"
    label: "Product Reviews"
    folder: "src/content/reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "description", label: "Description", widget: "text" }
      - { name: "image", label: "Image", widget: "image", required: false }
      - { name: "category", label: "Category", widget: "string" }
      - { name: "rating", label: "Rating", widget: "number", min: 1, max: 5 }
      - { name: "price", label: "Price", widget: "string" }
      - { name: "amazonUrl", label: "Amazon URL", widget: "string" }
      - { name: "pros", label: "Pros", widget: "list" }
      - { name: "cons", label: "Cons", widget: "list" }
      - { name: "bestFor", label: "Best For", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "publishDate", label: "Publish Date", widget: "datetime" }
      - { name: "body", label: "Body", widget: "markdown" }
